name: Build All

on:
  workflow_dispatch:
  create:
    tags:
      - "v*"

jobs:
  build:
    name: "Build all"
    runs-on: ubuntu-18.04
    steps:
      ###########################
      #        Setup env        #
      ###########################
      - uses: actions/checkout@v2
      - run: cat .env | sed 's/=\" *$/<<EOD/g' | sed 's/^\"/EOD/g' | grep '^[^# ]' >> $GITHUB_ENV

      - name: Get latest tag
        id: latest
        run: |
          LATEST_TAG=`git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='v:refname' --tags https://github.com/${{ github.repository }} 'v*.*' \
              | tail -n 1 \
              | cut -d '/' -f 3`
          echo $LATEST_TAG
          echo "::set-output name=tag::$LATEST_TAG"
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag }}

      ###########################
      #          Setup          #
      ###########################
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ steps.latest.outputs.tag }}
          restore-keys: ${{ runner.os }}-

      ###########################
      #  Build and push (Base)  #
      ###########################
      - uses: crazy-max/ghaction-docker-meta@v1
        id: base_docker
        with:
          images: ${{ env.BASE_IMAGE }}
      - name: Build (Base)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/base.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          labels: ${{ steps.base_docker.outputs.labels }}
          tags: ${{ steps.base_docker.outputs.tags }}

      ###########################
      #  Build and push (Hub)   #
      ###########################
      - uses: crazy-max/ghaction-docker-meta@v1
        id: hub_docker
        with:
          images: ${{ env.HUB_IMAGE }}
      - name: Build (Hub)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/hub.Dockerfile
          build-args: baseImage=${{ env.BASE_IMAGE }}:${{ steps.latest.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          labels: ${{ steps.hub_docker.outputs.labels }}
          tags: ${{ steps.hub_docker.outputs.tags }}

      ###########################
      # Build base editor image #
      ###########################
      - name: "Dispatch 'Build Editor' workflow"
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build Editor
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          inputs: '{ "module": "base", "repoTag": "${{ steps.latest.outputs.tag }}" }'
          ref: ${{ steps.latest.outputs.tag }}
