name: release

on:
  push:
    branches:
      - beta
      - main
      - v*.x
    tags-ignore:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]') && ! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Release
        id: release
        run: |
          npm ci
          npx semantic-release

          echo "::set-output name=tag::`git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='v:refname' --tags https://github.com/${{ github.repository }} 'v*.*' \
              | tail -n 1 \
              | cut -d '/' -f 3`"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "Dispatch 'Build All' workflow"
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build All
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          ref: ${{ steps.release.outputs.tag }}
